# -*- coding: utf-8 -*-
"""Lamda_function_Sagemaker_integration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TLNoMywshHCnUUIwY4ox7DDiUo5gC1Y6
"""

import os
import io
import boto3
import json

# grab environment variables
ENDPOINT_NAME = "sagemaker-scikit-learn-2022-03-21-03-53-55-462"
runtime= boto3.client('runtime.sagemaker')

def lambda_handler(event, context):
    print("Received event: " + json.dumps(event, indent=2))
    
    data = json.loads(json.dumps(event))
    payload = data['data']
    print(payload)
    
    response = runtime.invoke_endpoint(EndpointName=ENDPOINT_NAME,
                                       Body=json.dumps(payload))
    print(response)
    result = json.loads(response['Body'].read().decode())
    print(result)
    
    return result[0]